Issue 727
bitshares/bitshares-fc pull request #23
Opened 2018-03-22 13:55 UTC by jmjatlanta

This is the fc part of
https://github.com/bitshares/bitshares-core/issues/727

The code was gleaned from the steem project, and modified to fit our purposes. A license and contributors file was added to the fc project.

This PR also includes a tiny fix to a test (websocket_test.cpp) that was causing the only compiler warning for this project (on gcc at least).

2018-03-22 14:34 UTC, abitmore commented
Please check https://github.com/bitshares/bitshares-fc/pull/13 for more info about licensing issue. IMHO don't add LICENSE.md in this PR.

2018-03-23 16:35 UTC, pmconrad submitted a review, later dismissed
Please make your branch end at 6473e32 and force-push, I'd like to avoid having these licenses in our history.
Other than that looks good.

2018-03-23 19:24 UTC, jmjatlanta commented
Branch (and PR) reverted to https://github.com/bitshares/bitshares-fc/commit/6473e32f1e7bb9809f70dac89c6ad4613298671d

2018-03-23 20:24 UTC, abitmore submitted a review, later dismissed
Please remove the first commit which is related to websocket_test (rebase then force push) due to #30.

2018-03-23 20:51 UTC, pmconrad requested changes
The general quality of this looks rather poor to me.
Perhaps better use https://github.com/boostorg/stacktrace or sth like that?

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +      std::cerr << "print_stacktrace_linenums() failed, could not read PID" << std::endl;
Use elog() instead of cerr. I know that breaks the self-containment, but we're not using this as a standalone tool.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +   ss_cmd << "addr2line -p -a -f -C -i -e " << my_path;
This is a classic shell injection bug. Avoid creating subprocesses using functions that execute a string as a shell command. Use something like execvp instead.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +std::string run_command( const std::string& command )
Please make this function "static", it is not supposed to be used from outside.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +    char* funcname = (char*)malloc(funcnamesize);
This isn't free'd is something further down throws.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +    char** symbollist = backtrace_symbols(addrlist, addrlen);
This isn't free'd is something further down throws.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +   assert( max_frames <= 128 );
Replace this assert with an actual check that prevents crashes.

2018-03-23 20:51 UTC, pmconrad commented on src/stacktrace.cpp
> +   char** strs = backtrace_symbols( callstack, frames );
This isn't free'd is something further down throws.

2018-04-08 21:00 UTC, pmconrad commented
Closed in favor of a solution for boost >= 1.65

2018-04-08 21:00 UTC, closed without merging