unsigned_int unpacking
bitshares/bitshares-fc pull request #53
Opened 2018-05-31 01:14 UTC by oxarbitrage

https://github.com/bitshares/bitshares-core/issues/993

"varint decoding could over-shift a 32bit value, now it doesn't"

2018-06-01 18:40 UTC, jmjatlanta requested changes
Looks good, I wrote a sloppy test to prove that a malformed varint doesn't put the unpack in an endless loop. Please take a look and verify:

https://pastebin.com/Wz20wTxk

2018-06-01 18:48 UTC, jmjatlanta commented
I was thinking (always dangerous): What should we do when we are expecting a varint, and we get what we don't expect from the last byte? This code simply stops reading. Should an exception be thrown? 

The indication is that we're reading something bigger than what we expected, which indicates a corrupt stream or a number bigger than can fit in 4 bytes.

2018-06-02 09:28 UTC, abitmore commented
IMHO we should throw.

2018-06-05 14:17 UTC, pmconrad requested changes
We can't do that, it is a breaking change.
Unfortunately, we have no canonical serialized representation of numeric values, i. e. {0x80,...,0x80,0x0} currently is a valid representation of unsigned_int(0).

2018-06-07 19:52 UTC, pmconrad commented
I don't see how this could be done without breaking things (at least with reasonable effort). Since it is also not really a problem that needs fixing, I'm closing this PR. Please reopen if you think otherwise.

2018-06-07 19:52 UTC, closed without merging

2018-08-23 02:07 UTC, abitmore commented
Replaced by #64.