Get around boost 1.67 boost::filesystem::copy null pointer dereferencing issue
bitshares/bitshares-fc pull request #73
Opened 2018-08-09 17:08 UTC by abitmore

Replaces #42.

2018-08-09 20:08 UTC, pmconrad requested changes
As discussed on telegram, boost::system::system_error::what() returns a pointer to a null-terminated  C-string. FC_THROW wraps that pointer in a variant_object for later use, but the string it points to could go out of scope together with the caught exception. Please turn the C-string into a string again.
Same for boost::system::error_code::category().name() (watch out for NULL!).

2018-08-10 11:50 UTC, jmjatlanta commented on src/filesystem.cpp
> +	         ("srcfile",f)("dstfile",t)("reason",std::string(e.what()) ) );
I do not want to get into a long discussion about this, but I do not see how the c-string returned by e.what() has an opportunity to go out of scope before FC_THROW returns (barring threads, which I do not think are in play here). Therefore, I see the std::string(e.what()) as useless.

Now, I can see how using c-strings can cause scope issues before we enter the catch. But wrapping e.what() in std::string is closing the barn door after the cattle have left (see https://pastebin.com/nkKL8W9n ).

Someone please help me see the error in my thinking.

2018-08-10 15:31 UTC, jmjatlanta commented
I have determined that the boost bug reported at https://svn.boost.org/trac10/ticket/13585 has been there since at least 1.55. Evidently newer compilers are bringing this logic error to light. 

In a nutshell: 
``boost::filesystem::operations.cpp: void copy(const path& from, const path& to, system::error_code* ec) ``
dereferences ec when ec could be null. That is undefined behavior, and evidently now, a nearby crash.

Passing a non-null ec as this PR does avoids the issue.

2018-08-10 19:22 UTC, pmconrad commented on src/filesystem.cpp
> +	         ("srcfile",f)("dstfile",t)("reason",std::string(e.what()) ) );
FC_THROW "returns" by throwing a **new** exception. In my understanding, this makes the flow of control leave the catch block, and e goes out of scope.
The new exception thrown by FC_THROW wraps the original pointer, which remains dangling around after e has been destroyed.

2018-08-10 19:24 UTC, pmconrad approved these changes

2018-08-17 11:57 UTC, merged