Log console output during replay to file #985
bitshares/bitshares-fc pull request #76
Opened 2018-09-17 06:50 UTC by cogutvalera

PR for **"Log console output during replay to file #985 https://github.com/bitshares/bitshares-core/issues/985"**

2018-09-17 14:53 UTC, abitmore commented
Can you please briefly explain why change like this? There is no comment in your code.

2018-09-17 15:31 UTC, cogutvalera commented
I can add comments right into code if required. 
After debugging and researching code I've found the reason of this issue.
1. During `replay` we can see logs in console but not in file because of next reason: `fc::file_appender::impl::out` (`ofstream`) is opened after `rotate_files`. 
2. So this means that `ofstream` will be opened after `replay` is completed and finished. Thus after `replay` we can see the same logs in console and file.
3. Now after my changes `ofstream` is opened before `replay` happens. So this solution makes possible to see logs not only in console during `replay` but also we can see the same logs in file according to configuration in `config.ini` or `logging.ini`.

2018-09-17 20:17 UTC, jmjatlanta requested changes

2018-09-17 20:17 UTC, jmjatlanta commented on src/log/file_appender.cpp
> +            fc::scoped_lock<boost::mutex> lock( my->slock );
As this is a constructor, I do not see the need for a lock here.

2018-09-17 20:17 UTC, jmjatlanta commented on src/log/file_appender.cpp
> -         if(!my->cfg.rotate)
I haven't walked all of the code, but if rotate == true, will removing this cause open be called twice (once here, and once in rotate_files()) ?

2018-09-17 20:22 UTC, cogutvalera commented on src/log/file_appender.cpp
> -         if(!my->cfg.rotate)
`if rotate` check was removed, and twice won't be open because there is a check in `open_log_filename` method

2018-09-17 20:25 UTC, cogutvalera commented on src/log/file_appender.cpp
> +            fc::scoped_lock<boost::mutex> lock( my->slock );
we have different threads, that's why I've added lock here, IMHO `slock` mutex is supposed to be used for log files within different threads, maybe I'm wrong.

Thanks !

2018-09-18 21:25 UTC, abitmore submitted a review, later dismissed
Need better abstraction / modularization.

2018-09-18 21:25 UTC, abitmore commented on src/log/file_appender.cpp
> +         void open_log_filename()
This function name is confusing. I'd recommend rename it to `open_log_file()` or something else that can describe the logic better.

In addition, the check for file name inside the function made it even harder to understand, I think it would be better to move out the check, e.g. have an `open()` simply opens a file or perhaps close then reopen, and only call it when necessary (aka with a check).

In short, try to simplify the code.

2018-09-18 21:25 UTC, abitmore commented on src/log/file_appender.cpp
> +         fc::path                   _old_log_filename, _log_filename, _link_filename;
For member variables, please declare only one variable per line.

2018-09-18 21:25 UTC, abitmore commented on src/log/file_appender.cpp
> +      << " ";
The code style here looks a bit ugly. I'd prefer
```
line << "something"
     << "something else"
     << "the end";       
```

2018-09-18 21:25 UTC, abitmore commented on src/log/file_appender.cpp
>           fc::create_directories(my->cfg.filename.parent_path());
Why not move the whole logic into constructor of `impl` class for simplicity? All operation is done on `my` anyway.

2018-09-19 05:12 UTC, cogutvalera commented on src/log/file_appender.cpp
>           fc::create_directories(my->cfg.filename.parent_path());
I thought the same earlier, I agree it would be better ! Thanks !

2018-09-19 07:39 UTC, cogutvalera commented
pushed new commit **"more improvements"**

Thanks !

2018-09-19 15:55 UTC, pmconrad commented
> So this means that ofstream will be opened after replay is completed and finished.

Why is this so?
file_appender::impl calls rotate_files asynchronously from the constructor. Either there's something wrong with the call, or the async excution happens only after replay. In the latter case, the obvious (and much simpler) fix would be to make the initial rotate_files call synchronous.

2018-09-19 16:55 UTC, abitmore commented on src/log/file_appender.cpp
> +               FC_ASSERT( cfg.rotation_limit >= cfg.rotation_interval );
I think these assertions should be put before creating log file, even before `setup_log_filenames`.

2018-09-19 16:55 UTC, abitmore commented on src/log/file_appender.cpp
> +               std::cerr << "error opening log file: " << cfg.filename.preferred_string() << "\n";
Is the appender usable after caught an exception here? What will happen when trying to write?

2018-09-19 16:55 UTC, abitmore commented on src/log/file_appender.cpp
> +               }
The logic seems a bit strange.
* Is there a chance that the file got closed but not reopened?
* Is there a chance that the file be opened again when not closed?

2018-09-19 17:04 UTC, abitmore commented
> the obvious (and much simpler) fix would be to make the initial rotate_files call synchronous.

Probably because `rotate_files()` also removes old files that could take some time, thus not good to call on initialization. However, even it's the case, we can skip the removal on first call.

By the way, I guess the `rotate_files(1)` call is defensive? Looks like it will never be called.

2018-09-21 07:58 UTC, cogutvalera commented
(just for the info) I've pushed 2 new commits:

1. reverted all changes made before to current master branch
2. Log console output during replay to file #985 (2nd simpler solution)

2018-09-21 08:10 UTC, pmconrad requested changes
*If we decide to merge the second version*, you should ``rebase -i`` to get rid of the first version. But not yet.

2018-09-21 08:10 UTC, pmconrad commented on src/log/file_appender.cpp
> -         fc::create_directories(my->cfg.filename.parent_path());
I think this must be moved to impl::impl(), not simply removed.

2018-09-21 08:10 UTC, pmconrad commented on src/log/file_appender.cpp
> -         if(!my->cfg.rotate)
...and this shouldn't be removed.

2018-09-21 16:34 UTC, cogutvalera commented
> If we decide to merge the second version, you should rebase -i to get rid of the first version. But not yet.

IMHO the 2nd solution is simpler and it works as required, then why to rebase "not yet" ?

2018-09-24 18:31 UTC, pmconrad commented on src/log/file_appender.cpp
> +               fc::create_directories(cfg.filename.parent_path());
create_directories should happen before rotate_files.

2018-09-24 18:32 UTC, pmconrad commented
The idea was to preserve the original version in case my ideas didn't work. I'm ok with the rebase if it does work as intended.

2018-09-24 20:36 UTC, pmconrad approved these changes

2018-09-24 20:37 UTC, pmconrad commented
Thanks! @abitmore @jmjatlanta please re-review.

2018-09-25 18:15 UTC, jmjatlanta approved these changes

2018-09-25 18:19 UTC, jmjatlanta commented
There may be an edge case here that we may want to fix, but the chances of it happening are very remote. Scenario: Destructor called, then rotate_files gets the lock.

I am okay with that being there, as the file_appender is typically only destroyed at program exit, and the issue has probably been there from before this issue was opened.

2018-09-28 18:05 UTC, cogutvalera commented
@pmconrad @jmjatlanta Thanks guys !

2018-10-01 13:05 UTC, merged

2018-10-01 13:14 UTC, cogutvalera commented
Thanks !